FROM rubeus/node-npm
MAINTAINER rubeus <rubeusteam@gmail.com>

# Packages
RUN npm install -g @angular/cli

# Set up the volumes and working directory
VOLUME ["/app"]
WORKDIR /app

# Set up the command arguments
CMD ["-"]
