###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.1
      container_name: rb-mariadb10
      volumes:
        - ../../../bd-local:/var/lib/mysql
        - ../../../config/mariadb/my.cnf:/etc/mysql/my.cnf
      environment:
        - MYSQL_ROOT_PASSWORD=${RB_PASS_BD_DOCKER}
      ports:
        - "7003:3306"

    apache-php:
      image: rubeus/apache-php2
      container_name: rb-apache-php
      working_dir: /app
      environment:
        - APACHE_RUN_USER=${USERNAME}
        - APACHE_RUN_GROUP=root
      ports:
        - "7000:80"
      links:
        - mariadb
      volumes:
        - ../../../:/var/www/html
        - ../../../config/apache/log/:/var/log/apache2
        - ./php/php.ini:/etc/php5/apache2/php.ini
        - ./cacert.pem:/etc/ssl/certs/cacert.pem

networks:
  default:
    external:
      name: ambiente_dev
