FROM rubeus/node-npm
MAINTAINER rubeus <robloach@gmail.com>

# Packages
RUN npm install -g grunt-cli grunt

# Set up the volumes and working directory
VOLUME ["/app"]
WORKDIR /app

# Set up the command arguments
CMD ["-"]
